# Numpy -> Play with arrays(numbers)
# Pandas -> Dataset
# Matplotlib -> Data Visualization
# Seaborn -> Data Visualization
# Scipy -> Statistical
# Skilearn -> Algorithm

# Numpy: Package for Multidimensional Array

In [80]:
import numpy as np

In [81]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [82]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [83]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [85]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [86]:
np.arange(1,36,5) # shift+tab -> help box

array([ 1,  6, 11, 16, 21, 26, 31])

In [87]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [88]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [89]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [91]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [92]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [93]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [94]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [95]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [96]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [97]:
np.random.rand(3,5)

array([[0.35027448, 0.92908999, 0.61288514, 0.74312488, 0.24592418],
       [0.03952551, 0.69373205, 0.10480049, 0.79996243, 0.38338801],
       [0.80805388, 0.47592614, 0.18813153, 0.99242738, 0.75779342]])

In [98]:
arr=np.random.randn(2,4)
arr

array([[ 0.83007876,  1.95835126, -0.56153258, -1.02152533],
       [ 0.91666173,  0.64234852,  1.15318891,  1.18115737]])

In [99]:
np.random.randint(2,100)

67

In [100]:
np.random.randint(20,56,100)

array([55, 21, 28, 41, 49, 22, 22, 49, 51, 26, 37, 29, 50, 28, 50, 53, 45,
       34, 50, 32, 53, 28, 55, 28, 49, 22, 24, 23, 29, 24, 30, 39, 45, 33,
       22, 35, 55, 21, 49, 45, 22, 25, 51, 44, 44, 40, 41, 53, 31, 41, 24,
       25, 46, 36, 22, 28, 38, 32, 41, 28, 51, 29, 32, 24, 20, 26, 51, 32,
       47, 50, 33, 38, 47, 27, 31, 22, 44, 42, 24, 41, 24, 37, 51, 45, 40,
       44, 29, 25, 47, 50, 48, 52, 20, 32, 39, 41, 22, 42, 36, 42])

In [101]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [102]:
rand_array=np.random.randint(0,10,50)
rand_array

array([6, 5, 2, 0, 0, 3, 4, 7, 1, 5, 3, 4, 0, 5, 6, 7, 5, 1, 7, 8, 9, 1,
       6, 3, 1, 2, 9, 9, 5, 2, 5, 9, 9, 3, 0, 5, 7, 8, 0, 8, 8, 0, 9, 4,
       0, 3, 5, 8, 7, 4])

In [103]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [104]:
rand_array.max()

9

In [105]:
rand_array.argmin()

3

In [106]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [107]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [108]:
a=np.random.rand(2,3)
a

array([[5.53848876e-01, 2.99881707e-01, 8.09056462e-01],
       [6.35981601e-01, 1.00274872e-04, 6.35013894e-02]])

In [109]:
a.T

array([[5.53848876e-01, 6.35981601e-01],
       [2.99881707e-01, 1.00274872e-04],
       [8.09056462e-01, 6.35013894e-02]])

In [110]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [111]:
sample_array[0]

10

In [112]:
sample_array[2:5]

array([12, 13, 14])

In [113]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [114]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [115]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [116]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [117]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Two-Dimensional Array

In [118]:
import numpy as np

In [119]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [120]:
sample_matrix[1,2]

21

In [121]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [122]:
sample_matrix[2]

array([56, 76, 24,  7])

In [123]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

# Selection Techniques

In [124]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [125]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [126]:
np.exp(sample_array) #exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [127]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [128]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [129]:
np.max(sample_array)

19

In [130]:
np.min(sample_array)

1

In [131]:
np.argmax(sample_array)

18

In [132]:
np.argmin(sample_array)

0

In [133]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [134]:
np.std(sample_array) #standard deviation value

5.477225575051661

In [135]:
np.var(sample_array) #variance

30.0

In [136]:
np.mean(sample_array)

10.0

In [137]:
array=np.random.randn(3,4)
array

array([[-2.48328664, -0.30177771,  1.00710327, -0.48340966],
       [ 0.79526678,  0.90520814,  0.1880563 ,  1.6017434 ],
       [ 0.2174745 , -0.96336072,  0.00756558,  0.17098247]])

In [138]:
np.round(array,decimals=2)

array([[-2.48, -0.3 ,  1.01, -0.48],
       [ 0.8 ,  0.91,  0.19,  1.6 ],
       [ 0.22, -0.96,  0.01,  0.17]])

In [139]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

# Pandas

In [140]:
import pandas as pd
import numpy as np

# Pandas Dataframe and Indexing

In [141]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [142]:
sports1['football']

2

In [143]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [144]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [145]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.521460  0.481271  0.693454  0.618187  0.203111
B  0.138159  0.878982  0.446796  0.811910  0.885873
C  0.649401  0.792986  0.988582  0.473267  0.990631
D  0.975765  0.975341  0.697308  0.849874  0.390578
E  0.629228  0.162923  0.973816  0.277326  0.841614
F  0.067928  0.345077  0.638889  0.912510  0.801505
G  0.221632  0.947889  0.350886  0.766500  0.945099
H  0.765746  0.041406  0.522324  0.728965  0.398139

In [146]:
df1["Score1"]

A    0.521460
B    0.138159
C    0.649401
D    0.975765
E    0.629228
F    0.067928
G    0.221632
H    0.765746
Name: Score1, dtype: float64

In [147]:
df1[["Score1","Score2","Score3"]]

Score1    Score2    Score3
A  0.521460  0.481271  0.693454
B  0.138159  0.878982  0.446796
C  0.649401  0.792986  0.988582
D  0.975765  0.975341  0.697308
E  0.629228  0.162923  0.973816
F  0.067928  0.345077  0.638889
G  0.221632  0.947889  0.350886
H  0.765746  0.041406  0.522324

In [148]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.521460  0.481271  0.693454  0.618187  0.203111  1.002731
B  0.138159  0.878982  0.446796  0.811910  0.885873  1.017141
C  0.649401  0.792986  0.988582  0.473267  0.990631  1.442388
D  0.975765  0.975341  0.697308  0.849874  0.390578  1.951106
E  0.629228  0.162923  0.973816  0.277326  0.841614  0.792150
F  0.067928  0.345077  0.638889  0.912510  0.801505  0.413005
G  0.221632  0.947889  0.350886  0.766500  0.945099  1.169521
H  0.765746  0.041406  0.522324  0.728965  0.398139  0.807152

In [149]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavya','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavya      87
4  176  Lally     123

In [150]:
df["ID"]

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [151]:
df[["ID","Name"]]

ID   Name
0  101   John
1  102  Mercy
2  103  Akash
3  107  Kavya
4  176  Lally

In [152]:
df=df.drop("ID",axis=1)

In [153]:
df

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
3  Kavya      87
4  Lally     123

In [154]:
df.drop(3)

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
4  Lally     123